variable "enable_traefik" {}
variable "cluster_name" {}
variable "traefik_replica_count" {}
variable "cluster_issuer_email" {}
variable "tiller_service_account" {}
variable "kubeconfig_path" {}
variable "host" {}
variable "cluster_ca_certificate" {}
variable "cluster_client_certificate" {}
variable "cluster_client_key" {}
variable "username" {}
variable "password" {}
