---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-app
  namespace: healthcheck
  labels:
    createdby: terraform
    datacenter: cluster # "${var.cluster_name}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hc-app
  template:
    metadata:
      labels:
        app: hc-app
        createdby: terraform
        datacenter: cluster # "${var.cluster_name}"
    spec:
      serviceAccountName: healthcheck
      containers:
      - name: hc
        image: emrekenci/k8s-healthcheck:v1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 5000
        env:
          - name: USERNAME
            value: admin
          - name: PASSWORD
            value: randmon
          - name: CACHE_DURATION_IN_SECONDS
            value: "30"
          - name: NODE_ENV
            value: production
          - name: EXCLUDE
            value: controllerManager,scheduler
          - name: DEPLOYMENTS_NAMESPACE
            value: default
