config:
  specifiedInValues: true
  value: {}

labels:
  prometheus-operated: "true"

externalLabels: {}

externalUrl: ""

selfServiceMonitor: false

image:
  repository: quay.io/prometheus/prometheus
  tag: v2.2.1

## If true, the Operator won't process any Prometheus configuration changes
##
paused: false
global:
  rbacEnable: false
  pspEnable: false

serviceAccount:
  create: true

replicaCount: 1
logLevel: info
podAntiAffinity: "soft"
remoteRead: {}
remoteWrite: {}
retention: 24h
routePrefix: /

## Prometheus alerting & recording rules
## Ref: https://prometheus.io/docs/querying/rules/
## Ref: https://prometheus.io/docs/alerting/rules/
##
rules:
  specifiedInValues: false
  additionalLabels: {}
  value: {}
service:
  sessionAffinity: None
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []
  type: ClusterIP