## Alertmanagers to which alerts will be sent
## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerendpoints
##
alertingEndpoints: []
#   - name: ""
#     namespace: ""
#     port: http
#     scheme: http

config:
  specifiedInValues: true
  value: {}

externalLabels: {}

externalUrl: ""

selfServiceMonitor: false

image:
  repository: quay.io/prometheus/prometheus
  tag: v2.2.1

## If true, the Operator won't process any Prometheus configuration changes
##
paused: false
global:
  rbacEnable: false
  pspEnable: false

serviceAccount:
  create: true
  name: ""

replicaCount: 1
logLevel: info
podAntiAffinity: "soft"
remoteRead: {}
remoteWrite: {}
retention: 24h
routePrefix: /

## Prometheus alerting & recording rules
## Ref: https://prometheus.io/docs/querying/rules/
## Ref: https://prometheus.io/docs/alerting/rules/
##
rules:
  specifiedInValues: false
  additionalLabels: {}
  value: {}
service:
  sessionAffinity: None
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []
  type: ClusterIP

additionalScrapeConfigs:
- job_name: 'federate'
  scrape_interval: 15s

  honor_labels: true
  metrics_path: '/federate'

  params:
    'match[]':
      - '{job="prometheus"}'
      - '{__name__=~"traefik.*"}'

  static_configs:
    - targets:
      - 'GKE_CLUSTER_PROMETHEUS_SVC_IP:9090'
      - 'AKS_CLUSTER_PROMETEHUS_SVC_IP/DNS:9090'