# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: monitoring
spec:
  strategy: production
  agent:
    strategy: DaemonSet
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-elasticsearch-client.elasticsearch:9200
