{
 "title": "Traefik  Realtime Stats",
 "description": "Visualize Traefik Health Metrics",
 "tags": [
  "traefik",
  "load-balancer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total) by (job, datacenter)\n",
     "legendFormat": "{{ datacenter }}: {{ job }}"
    }
   ]
  },
  {
   "title": "Backend avg. response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(traefik_backend_request_duration_seconds_sum ) by (job, datacenter)) / (sum(traefik_backend_requests_total) by (job, datacenter))",
     "legendFormat": "{{ datacenter }}:{{job}}"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m])) by (job, datacenter)",
     "legendFormat": "{{ datacenter }}: {{job}} "
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{protocol=~\"http|https\",code=\"200\"}[5m])) by (backend,method,job,datacenter)",
     "legendFormat": " {{datacenter}}: {{service}} {{method}}-{{job}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{protocol=~\"http|https\",code!=\"200\"}[5m])) by (backend,method,code,job,datacenter) ",
     "legendFormat": "{{datacenter}}: {{backend}} {{method}} {{code}}-{{job}}"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds ", "legendFormat": "{{instance}}:{{ job }}" }
   ]
  }
 ]
}