variable "client_certificate" {}
variable "client_key" {}
variable "cluster_ca_certificate" {}
variable "host" {}
variable "enable_traefik" {}
variable "enable_prometheus" {}
variable "cluster_name" {}
variable "traefik_replica_count" {}
variable "registry_url" {}
